services:
  backend:
    build: ./backend
    container_name: jqh-backend
    restart: always
    env_file:
      - .env
    expose:
      - "8080"

  frontend:
    build: ./frontend
    container_name: jqh-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
